### ISSUE TITLE
code line #19 

### ISSUE THREAD

**Issue by ChristinaRita** [olaadapo/scrape-news-articles#1]
Hi! First of all, thank you for this code! 

However, the code line 19, doesn't work for me. The code runs without any errors but it gives me an empty list! Could you explain what could be my mistake? Should I change something in the way you wrote your code? Thank you!

**Comment by olaadapo** [comment]
Thank you, Christina. Unfortunately, the Quartz web page has been edited since this code was created, and a lot of the HTML tags and class and id attributes have been changed. This means, for most of the sections, there are no elements matching the specified class attributes on the page, hence the empty lists.

To apply this to your case, I would suggest inspecting the page to make sure you have the right class attributes, and this should work fine. In the meantime, I'll try to put up an updated version of getting articles from Quartz.
